### PR TITLE
Added a new Pagic command to generate mod.ts

### PR DESCRIPTION
**Pull request by MVEMCJSUNPE**
This is supposed to 'ease some burdens' for shah
as mentioned in issue #47 , although
I'm hesitant to outright say it completely resolves
the issue. Users can now write 'pagic genmod' to
automatically generate a mod.ts in their theme
directory.

### CODE REVIEW

**Comment by xcatliu** [comment]
I would consider to rename this subcommand to `pagic init` and give some interactive way to init a `pagic.config.ts` or `pagic.config.tsx` or `mod.ts` etc.

But I haven't find a third party module to write some interactive user interface like [commander](https://github.com/tj/commander.js/)

If you are interested, welcome to implement this `pagic init` command

**Comment by MVEMCJSUNPE** [comment]
Deno actually has a few modules to write an interactive user interfaces, I think. There's [cmd](https://deno.land/x/cmd@v1.2.0) which is basically Commander for Deno and [cliffy](https://deno.land/x/cliffy@v0.14.3), but cmd seems like the safest option. How should the user decide between pagic.config.ts, pagic.config.tsx, and mod.ts though? "pagic init" doesn't seem like it provides enough information for deciding between pagic.config.ts, pagic.config.tsx, and mod.ts, and I'm not sure if there is a way to automatically detect the right kind of config file.

**Comment by xcatliu** [comment]
> How should the user decide between pagic.config.ts, pagic.config.tsx, and mod.ts though?

What I mean is something like [this](https://cli.vuejs.org/guide/creating-a-project.html#vue-create):

image

Is there any deno module can achieve this?

**Comment by MVEMCJSUNPE** [comment]
I think cliffy has something similar: [prompt](https://github.com/c4spar/deno-cliffy/tree/master/prompt)

**Comment by xcatliu** [comment]
[prompt](https://github.com/c4spar/deno-cliffy/tree/master/prompt) looks good

**Comment by xcatliu** [comment]
@MVEMCJSUNPE I've added some tests to master branch. Please merge it again and I'll review this pr.

**Comment by MVEMCJSUNPE** [comment]
I made some commits, so feel free to take a look

**Comment by xcatliu** [comment]
@MVEMCJSUNPE Please merge master to your branch to fix the ci errors.

**Comment by MVEMCJSUNPE** [comment]
sorry, my bad

**Review by xcatliu — APPROVED** [review]

**Pull request merged**
